assets/styles/components/_AffiliateDuo.scss
assets/styles/components/_MerchantAffiliate.scss
assets/styles/elements/_Typography.scss

Adding animation to top header, few changes to Tour page
**Checklist**
Close QualityUnit/la-marketing#1993

[1993] Adding animation to top header, few changes to Tour page

---

assets/scripts/custom/IconTabs.js
functions/content-filters.php
functions/lazy-load.php

changes to make lazyload working again
**Checklist**
Close QualityUnit/web-issues#471

fix: changes to make lazyload working again

---

assets/styles/components/_AffiliateDuo.scss
assets/styles/components/_BlockPricingNew.scss
assets/styles/components/_MerchantAffiliate.scss
assets/styles/elements/_Typography.scss

Small changes to Tour page styles
Compare with design vs. Laci comments on:
https://www.figma.com/file/0sYJczXCmudr1uMkc6EFWv/PAP-WEB-RfD---Take-a-tour?node-id=105%3A916
**Checklist**
Close QualityUnit/la-marketing#1993

[1993] fix: small changes to Tour page styles

---

lib/metaboxes/features.php
templates/content-archive-ms_features.php

Changed filter plans to match Pap
fixed features metabox
We need to fix each feature in database accordingly
**Checklist**
Close QualityUnit/web-issues#456

[456] Fixing LA plans showing up instead of Pap ones

---

functions/rest-api.php

Fix: include integration methods files
**Checklist**

fix: include integration methods files

---

lib/shortcodes/language-switcher.php

Fix header language switcher
**Checklist**
Close QualityUnit/web-issues#477

[477] fix: header language switcher

---

templates/content-single-ms_directory.php

Add urlslab screenshot to directories
**Checklist**

feat: add urlslab screenshot to directories

---

assets/styles/components/_CTA.scss

Added margin top on image
**Checklist**
Close QualityUnit/web-issues#463

Changes in PAP banner

---

assets/styles/layouts/_Header.scss

Added support for "More integrations" button in main naviation
Its needed to add it into menu in WP with classname "button-more-integrations".
**Checklist**
Close QualityUnit/web-issues#478

[478] feat: Added support for more integrations button in main navigation

---

lib/includes/affiliate-manager.php
templates/content-single-ms_directory.php

Added support for gravatar photos in affiliate manager page.
You can find example of it on [/affiliate-program-directory/24pokies-help-desk-contacts/](http://localhost:3000/affiliate-program-directory/24pokies-help-desk-contacts/)
& [/affiliate-manager/24pokies-affiliate-program-contact/](http://localhost:3000/affiliate-manager/24pokies-affiliate-program-contact/)
**Checklist**
Close QualityUnit/web-issues#422

[422] feat: Added support for gravatar

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.4
**Checklist**

feat: bump version to 1.0.4

---

functions/lazy-load-youtube-microdata.php

fix: caching youtube video data
**Checklist**
Close QualityUnit/web-issues#465

[465] fix: caching youtube video data

---

.github/dependabot.yml

- change dependabot settings
**Checklist**

chore: change dependabot settings

---

assets/scripts/static/crm.js
base.php
lib/shortcodes/signup-form-trial.php
templates/footer.php

Pap tracking with/without cookie, same id fix
**Checklist**
Close QualityUnit/web-issues#500

[500] fix: pap tracking with/without cookie, same id fix

---

assets/styles/layouts/_Header.scss

Adjusted height of hover effect on more integrations button
**Checklist**

style: adjusted height of hover effect on more integrations button

---

assets/styles/common/_global.scss
assets/styles/pages/Directory.scss
templates/content-single-ms_directory.php

Adding content to affiliate directories
Check ie, https://admin.postaffiliatepro.com/affiliate-program-directory/casino-empire-affiliate-program/ of whether the content under each subtitle is set according to https://docs.google.com/document/d/1WfLAgXHm8EMbzlhw_A-dajCNmXuMUeBYwevi_ih6Buc/edit
**Checklist**
Close QualityUnit/web-issues#458

[458] feat: adding content to affiliate directories

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.11
**Checklist**

chore: bump theme version to 1.0.6

---

base.php

pap tracking script on cookie accept
Verify if tracking event is sent upon Cookie accept (in incognito) in Network panel of the browser without parameter mode=SC
**Checklist**
Close QualityUnit/web-issues#500

[500] fix: pap tracking script on cookie accept

---

assets/styles/components/_CategorySidebar.scss

smaller vertical space and border radius of left menu items
please check if changes are visually ok
**Checklist**
Close QualityUnit/web-issues#482

fix: smaller vertical space of left menu items

---

assets/styles/layouts/_BlogPost.scss
templates/content-single.php

Blog category fix for urls not closed properly after regex
**Checklist**
Close QualityUnit/web-issues#[ISSUE_NUMBER]

[554] Blog category fix

---

CHANGELOG.md
functions.php
style.css

bump theme version to v1.0.7
**Checklist**

chore: bump theme version to 1.0.7

---

lib/shortcodes/copy.php

html encoding for textarea
**Checklist**
Close QualityUnit/web-issues#544

[544] fix: html encoding for textarea

---

assets/styles/layouts/_Header.scss

header description text overflow and color
**Checklist**
Close QualityUnit/web-issues#529

[529] fix: header description text overflow and color

---

elementor.php
template-academy.php
template-blog.php
templates/content-page.php
templates/content-single-ms_academy.php
templates/content-single-ms_features.php
templates/content-single-ms_glossary.php
templates/content-single-ms_integrations.php
templates/content-single-ms_research.php
templates/content-single-ms_templates.php
templates/content-single.php

implement urlslab plugin as related resources source
**Checklist**

feat: implement urlslab plugin as related resources source

---

assets/styles/components/_HeaderLanguageSwitcher.scss

language switcher flag fix
Close QualityUnit/web-issues#535

[535] fix: language switcher

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.9
**Checklist**

chore: bump theme version to 1.0.9

---

assets/styles/pages/Directory.scss
templates/content-single-ms_directory.php

Add related resources to Directory
Add link to website screenshot in Directory
E.g. [this URL](http://postaffiliatepro.local/affiliate-program-directory/advertise-pro-affiliate-program/).
**Checklist**
Close QualityUnit/web-issues#594

[594] feat: add related resources to directory

---

functions/lazy-load-youtube-microdata.php

removing yt microdata cache refresh
**Checklist**
Close QualityUnit/web-issues#465

[465] fix: removing yt microdata cache refresh

---

assets/scripts/custom/filter.js
assets/styles/components/_CategoryHeader.scss
templates/content-archive-ms_academy.php

Header subtitle top margin was increased
Filter counter fixed
Items tag names fixed
Test Academy page and check changes
**Checklist**
Close QualityUnit/web-issues#608

[608] Academy small bug fixes

---

templates/content-archive-ms_integrations.php

Integrations page subtitle changed
Check subtitle on Integrations page
**Checklist**
Close QualityUnit/web-issues#563

[563] Subtitle on Integration page

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.10
**Checklist**

chore: bump theme version to 1.0.10

---

lib/widgets/qu-howtos/src/scss/_editor-styles.scss
lib/widgets/qu-howtos/src/scss/_howto.scss
lib/widgets/qu-howtos/src/scss/editor.scss
lib/widgets/qu-howtos/webpack.config.js

How to text formatting
**Checklist**
Close QualityUnit/web-issues#610

[610] fix: how to text formatting

---

assets/styles/pages/Directory.scss
templates/content-single-ms_directory.php

safari hover on directory screenshot
**Checklist**
Close QualityUnit/web-issues#490

[490] fix: safari hover on directory screenshot

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.11
**Checklist**

chore: bump theme version to 1.0.11

---

functions/lazy-load-youtube-microdata.php

Rewriting regex for schema/lazy to dom parser
**Checklist**

fix: rewriting regex for schema/lazy to dom parser

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.12
**Checklist**

chore: bump theme version to 1.0.12

---

lib/metaboxes/directory.php
templates/content-single-ms_directory.php

Allow program url to be optionally follow/nofollow
**Checklist**
Close QualityUnit/web-issues#622

[622] feat: allow program url to be optionally follow/nofollow

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.13
**Checklist**

chore: bump theme version to 1.0.13

---

assets/styles/elements/_Typography.scss

Removed icon of external link beneath pictures uploaded on our cdn
Check if thoso icons disappeared e.a. on [blog](http://postaffiliatepro.local/blog/things-to-look-for-in-an-affiliate-agreement/)
**Checklist**
Close QualityUnit/web-issues#565

[565] fix: removed external link icon for uploads on our cdn

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.14
**Checklist**

chore: bump theme version to 1.0.14

---

assets/styles/components/_CategoryItem.scss
templates/content-archive-ms_templates.php

Show template category and changed image gradient
Check templates list functionality and implemented design
**Checklist**
Close QualityUnit/web-issues#696

[696] how template category and changed image gradient

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.15
**Checklist**

chore: bump theme version to 1.0.15

---

lib/includes/affiliate-manager.php
lib/metaboxes/affiliate-manager.php

- fix of not saving title of an affiliate manager
**After release instructions**
- we need to re-enter the name of each affiliate manager
**Checklist**
Close QualityUnit/web-issues#692

[692] fix: fix of not saving title of affiliate manager

---

templates/content-single-ms_directory.php

Affiliate program changes in wording
**Checklist**
Close QualityUnit/web-issues#666

[666] Affiliate program changes

---

assets/styles/components/_Boxes.scss
assets/styles/components/_PapPanHomeSplit.scss

Change styles of home sections according to issue
Check changes and compare them with design
**Checklist**
Close QualityUnit/web-issues#721

[721] homepage sections look

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.16
**Checklist**

chore: bump theme version to 1.0.16

---

assets/scripts/custom/slider.js
assets/styles/common/_variables.scss
assets/styles/common/splide.scss
assets/styles/components/AwardsSmall.scss
assets/styles/components/IconTabs.scss
assets/styles/components/_Block.scss
assets/styles/components/_HorizontalTabs.scss
assets/styles/components/_Reference.scss
assets/styles/elements/_Button.scss
assets/styles/elements/_Typography.scss
functions/shortcodes.php
lib/shortcodes/awards-small.php
lib/shortcodes/slider-testimonials-reference.php

Aff software page redesign, carousel
**Checklist**
Close QualityUnit/web-issues#664

[664] feat: aff software page redesign, carousel

---

base-scripts.php

New gtag AW-942942148 was added and old tags was removed.
Check if new gtag working properly.
**Checklist**
Close QualityUnit/web-issues#743

[743] GTM scripts

---

CHANGELOG.md
assets/styles/elements/_Button.scss
functions.php
style.css

Fixing button class name for different button size
**Checklist**
Close QualityUnit/web-issues#767

[767] fix: button class name

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.19
**Checklist**

chore: bump theme version to 1.0.19

---

assets/styles/components/_Block.scss

Display of Box-primary in Block--lines on mobile was fixed.
Check Box-primary in Block--lines on mobile.
Check pages:
[Affiliate Tracking Software](https://www.postaffiliatepro.com/affiliate-tracking-software/)
[Integration](https://www.postaffiliatepro.com/services/integration/)
[Automation](https://www.postaffiliatepro.com/automation/)
**Checklist**
Close QualityUnit/web-issues#799

[799] Box-primary in Block--lines on mobile

---

assets/styles/components/_CategoryItem.scss

Features align was fixed on mobile.
Check Features landing page and features list on mobile.
**Checklist**
Close QualityUnit/web-issues#802

[802] Feature on mobile

---

assets/styles/common/_variables.scss
assets/styles/elements/_Checklist.scss

Larger spaces between elements.
Changed vertical position of bullet in checklists.
Check paragraph spaces and bullets position in texts on the web.
**Checklist**
Close QualityUnit/web-issues#673

[673] Larger spaces between elements

---

assets/styles/common/_variables.scss
assets/styles/components/_Block.scss
assets/styles/components/_BlockChannels.scss
assets/styles/components/_BlockPoints.scss
assets/styles/components/_BlockPricing.scss
assets/styles/components/_BlockSolutions.scss
assets/styles/components/_Box.scss
assets/styles/components/_Faq.scss
assets/styles/components/_Reviews.scss
assets/styles/components/_Text.scss

New spaces between blocks.
Check spaces between sections and blocks across entire web.
**Checklist**
Close QualityUnit/web-issues#674

[674] Margins between blocks

---

assets/styles/pages/About.scss
assets/styles/pages/Directory.scss
lib/includes/affiliate-manager.php
lib/metaboxes/affiliate-manager.php
taxonomy-ms_directory_affiliate_manager.php

New checkbox field to hide Bio for Affiliate Managers was added
Test hide functionality for Bio section in Affiliate Manager
**Checklist**
Close QualityUnit/web-issues#762

[762] New checkbox field to hide Bio for Affiliate Managers

---

assets/styles/components/_ExtraFaq.scss

Fixed font family in heading so its unified
**Checklist**
Closes https://github.com/QualityUnit/web-issues/issues/786

[786] fix: applied same font family for whole headline

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.0.20
**Checklist**

chore: bump theme version to 1.0.20

---

assets/styles/common/_variables.scss
assets/styles/components/_Block.scss
assets/styles/components/_HeroHeadlineHome.scss
assets/styles/components/_PapPanHomeSplit.scss

Hero section bottom space.
Logos section vertical space.
Check spaces between hero sections and logos sections on the web.
**Checklist**
Close QualityUnit/web-issues#800

[800] Hero bottom space

---

CHANGELOG.md
assets/scripts/custom/IconTabs.js
functions.php
style.css

icontab chart not loading
**Checklist**

fix: icontab chart not loading

---

assets/styles/components/_ExtraFaq.scss
assets/styles/layouts/_Post.scss
lib/shortcodes/extra-faq.php
template-academy.php
template-blog.php
templates/content-single-ms_academy.php
templates/content-single-ms_directory.php
templates/content-single-ms_features.php
templates/content-single-ms_glossary.php
templates/content-single-ms_integrations.php
templates/content-single-ms_research.php
templates/content-single-ms_templates.php
templates/content-single.php
yarn.lock

(fix: faq and related res. width)
**Checklist**
Close QualityUnit/web-issues#730

[730] fix: width of faq items

---

.gitignore
composer.json
composer.lock
functions/content-filters.php
gulpfile.js
lib/shortcodes/language-switcher.php

Implementation for SVG Icons sprite support
**Checklist**

[815] SVG icons sprite

---

CHANGELOG.md
functions.php
style.css

bump theme version to 1.2.0
**Checklist**

chore: bump theme version to 1.2.0

---

assets/styles/layouts/_Header.scss
composer.lock
gulpfile.js

implemented svg icons in the  main menu
**Checklist**
Close QualityUnit/web-issues#815

[815] fix: implemented svg icons in the  main menu

---

assets/styles/layouts/_Header.scss
assets/styles/pages/Directory.scss
lib/includes/affiliate-manager/affiliate-manager-layout.php

Affiliate directory manager small changes
**Checklist**
Close QualityUnit/web-issues#846

[846] fix: affiliate directory manager

---

functions/content-filters.php

schema url in hostname
**Checklist**
Close QualityUnit/web-issues#734

[724] fix: schema url in hostname

---

assets/styles/layouts/_Post.scss

Fixed logos' aspect ratio in integrations detail in header.
Check logos appearance in integrations detail.
**Checklist**
Close QualityUnit/web-issues#725

[725] Fixed logos' aspect ratio in integrations detail

---

assets/scripts/custom/sidebar_items_slider.js
assets/scripts/custom/sidebar_toc.js

[Describe what was changed in the Pull Request](fix: images loading 2x with sidebar)
**Checklist**
Close QualityUnit/web-issues#878

[878] fix: images loading 2x with sidebar

---

CHANGELOG.md
functions.php
lib/widgets/qu-howtos/yarn.lock
style.css

bump theme version to 1.3.0
**Checklist**

chore: bump theme version to 1.3.0

---

lib/shortcodes/signup-sidebar.php
templates/content-archive-ms_academy.php
templates/content-archive-ms_features.php
templates/content-archive-ms_integrations.php
templates/content-archive-ms_templates.php
templates/content-archive.php
templates/footer.php
templates/header.php

Describe what was changed in the Pull Request
**Checklist**
https://github.com/QualityUnit/web-issues/issues/903

fix: rename urlslab-skip to urlslab-skip-all

---

assets/styles/elements/_Checklist.scss

Fixed styling of tooltips in checklists.
Check tooltips on [Pricing](http://postaffiliatepro.local/pricing/) page.
**Checklist**
Close QualityUnit/web-issues#[ISSUE_NUMBER]

[835] Checklist tooltip styling fix

---

assets/scripts/app/signup_login_js_loader.js
assets/scripts/custom/sidebar_items_slider.js

loading crm and other scripts solution
**Checklist**
Close QualityUnit/web-issues#880

[880] fix: signup and other scripts loading on sidebar

---

functions/post-query-mods.php

Asc. order of integrations posts on [Integrations](https://www.postaffiliatepro.com/integration-methods/) page.
Check order of integrations posts on [Integrations](https://www.postaffiliatepro.com/integration-methods/) page.
**Checklist**
Close QualityUnit/web-issues#863

[863] asc order of integrations posts

---

assets/images/dotted-line.svg
assets/styles/pages/Directory.scss
lib/includes/affiliate-manager/affiliate-manager-layout.php
templates/content-single-ms_directory.php

Style of dotted line in Directories blocks titles was fixed and optimized.
Check dotted line in directories block titles
**Checklist**
Close QualityUnit/web-issues#829

[829] Directory detail titles styles

---

assets/styles/common/_lightbox.scss

lightbox for modal dialog (aff manager dir)
**Checklist**

fix: lightbox for modal dialog (aff manager dir)

---

.eslintrc
assets/scripts/custom/blogLazyLoad.js

adding missing  function to bloglazyload js
**Checklist**
Close QualityUnit/web-issues#904

[904] fix: adding missing  function to bloglazyload js

---

assets/scripts/static/crm.js
lib/shortcodes/signup-form-network.php
lib/shortcodes/signup-form-trial.php
lib/shortcodes/signup-form.php
lib/shortcodes/signup-sidebar.php

- set max length for name and mail input
- allow using dash in the domain field
- don't allow to use dot in the name field
**Checklist**
Close QualityUnit/web-issues#897
Close QualityUnit/web-issues#910
Close QualityUnit/web-issues#932

[897, 910, 932] Trial Signup Improvements and Fixes

---

assets/styles/components/_HeroHeadlineHome.scss

Hero image with border radius
Check border radius in hero images
**Checklist**
Close QualityUnit/web-issues#933

[933] Hero image with border radius

---

gulpfile.js
package.json
template-academy.php
template-blog.php
yarn.lock

Fixing function for icons.svg generation and IDs, adding sidebar and signupform css to templates
**Checklist**

fix: icons generator, adding css files

---

assets/scripts/custom/countdown.js
assets/styles/app.scss
assets/styles/components/BlockCoupon.scss
assets/styles/elements/_Checklist.scss
assets/styles/elements/_Typography.scss
assets/styles/shortcodes/Countdown.scss
functions/components-import.php
functions/shortcodes.php
lib/includes/affiliate-manager/affiliate-manager-layout.php
lib/pagesources.php
lib/shortcodes/countdown.php
templates/content-archive.php
templates/content-single.php

Fixes for missing styles and adding countdown (black friday) banner CSS and JS
**Checklist**

feat: added countdown banner and missing css fixes

---

assets/scripts/app/stickyViaAbsolute.js
assets/styles/components/Filter.scss
assets/styles/layouts/Header.scss
assets/styles/pages/Archive.scss
composer.lock
gulpfile.js
lib/includes/affiliate-manager/affiliate-manager.php
lib/includes/affiliate-manager/archive.php
templates/content-archive-ms_directory.php
templates/content-single-ms_directory.php

Multiple small changes on PAP Affiliate directory
**Checklist**
Close QualityUnit/web-issues#950

[950] Directory design changes

---

assets/styles/components/Filter.scss
assets/styles/layouts/_AffiliateManagerDirectory.scss
lib/includes/affiliate-manager/archive.php
templates/content-archive-ms_directory.php

header tags and filter position
**Checklist**
Close QualityUnit/web-issues#972

[972] fix: header tags and filter position

---

assets/styles/layouts/_AffiliateManagerDirectory.scss
assets/styles/layouts/_FullScreen.scss
assets/styles/pages/Archive.scss
assets/styles/pages/Directory.scss

new hover for screenshot image in directory
**Checklist**
Close QualityUnit/web-issues#948
Close QualityUnit/web-issues#949
Close QualityUnit/web-issues#946

[948] fix: new hover for screenshot image in directory

---

assets/styles/shortcodes/CTA.scss
lib/shortcodes/cta.php

CTA banner visuals
**Checklist**
Close QualityUnit/web-issues#967

[967] fix: CTA banner visuals

---

templates/content-archive-ms_features.php

Adding title to read more button
**Checklist**
Close QualityUnit/web-issues#977

[977] feat: adding title to read more button

---

composer.lock

Updated composer lock file.
Check icons on redesigned landing pages
**Checklist**
Close QualityUnit/web-issues#806

[806] Updated composer lock for redesigned landing pages

---

assets/styles/components/_HeroHeadlineHome.scss

Home hero icons fix
Check icons in home hero section
**Checklist**
Close QualityUnit/web-issues#806

[806] Home hero icons fix

---

lib/extras.php

adding true parameter to recognize full url even with query hash
**Checklist**
Close QualityUnit/web-issues#984

[984] fix: adding true parameter to recognize full url even with query hash

---

assets/styles/common/_elementor.scss
assets/styles/components/HorizontalTabs.scss
assets/styles/components/_Block.scss
assets/styles/components/_BlockIcons.scss

Changes on landing pages according to figma comments.
Check changes on landing pages:
https://admin.postaffiliatepro.com/home-2/
https://admin.postaffiliatepro.com/affiliate-tracking-software-2/
https://admin.postaffiliatepro.com/affiliate-marketing-software-2/
**Checklist**
Close QualityUnit/web-issues#907

[907] PAP landing pages redesign review feedback

---

assets/styles/components/FormPopup.scss
assets/styles/components/_Login.scss
gulpfile.js
lib/includes/affiliate-manager/archive.php
lib/shortcodes/login.php
package.json
templates/content-archive-ms_directory.php
yarn.lock

multiple css fixes, added dynamic paths in urls in css
**Checklist**
Close QualityUnit/web-issues#1012
Close QualityUnit/web-issues#1013
Close QualityUnit/web-issues#1017

[1012] fix: multiple css fixes, added dynamic paths in urls in css

---

assets/styles/common/_elementor.scss
assets/styles/common/_mixins.scss
assets/styles/components/BlockPricingNew.scss
assets/styles/components/HorizontalTabs.scss
assets/styles/components/_Block.scss
assets/styles/components/_BlockIcons.scss
assets/styles/components/_Boxes.scss

Final changes on homepage and landing pages.
Check and test changes
**Checklist**
Close QualityUnit/web-issues#907

[907] Landing pages redesign review feedback

---

templates/footer.php

Footer contacts numbers and text fixes.
Check footer content.
**Checklist**
Close QualityUnit/web-issues#952

[952] Footer content changes

---

assets/styles/components/_Newsletter.scss
assets/styles/layouts/Footer.scss
templates/footer.php

Small footer layout changes.
Check footer layout according [figma](https://www.figma.com/file/YvMUSLzVDPvbD4DezAvJfG/PAP-WEB-RfD---Homepage?node-id=227%3A369&t=OkOtB45hTNZDpuVe-0) file.
**Checklist**
Close QualityUnit/web-issues#952

[952] Footer pixhunt

---

templates/content-archive-ms_glossary.php
templates/content-single-ms_directory.php
templates/content-single-ms_integrations.php

- remove utm params from urls
- change glossary archive title
**Checklist**
Close QualityUnit/web-issues#1036
Close QualityUnit/web-issues#1038

[1036, 1038] SEO Improvements

---

assets/styles/layouts/Footer.scss
templates/footer.php

Compact footer height
Check footer styles
**Checklist**
Close QualityUnit/web-issues#952

[952] Compact footer height

---

assets/scripts/app/app.js
assets/styles/components/HorizontalTabs.scss

horizontal tabs not working when user not logged in
**Checklist**
Close QualityUnit/web-issues#1042

[1042] fix: horizontal tabs when user not logged in

---

functions/content-filters.php

remove duplicate x-default hreflang link
**Checklist**
Close QualityUnit/web-issues#1030

[1030] fix: remove duplicate x-default hreflang link

---

assets/styles/pages/AffiliateManager.scss
lib/includes/affiliate-manager/affiliate-manager-layout.php

remove back button from affiliate manager
**Checklist**
Close QualityUnit/web-issues#1029

[1029] fix: remove back button from affiliate manager

---

contactus-box.php

contact form ids by language
**Checklist**
Close QualityUnit/web-issues#1027

[1027] fix: contactus form id by language

---

assets/styles/components/BlockPricingNew.scss

Changes in pricing section in DE website:
* font sizes
* text colors in paragraphs
Check pricing block styles.
**Checklist**
Close QualityUnit/web-issues#1046

[1046] DE Domain Changes

---

assets/styles/common/_mixins.scss
assets/styles/components/BoxesStars.scss
assets/styles/elements/_Typography.scss
functions/content-filters.php

Learn more mixin with arrow from icons.svg file.
Check learn more arrows on web.
**Checklist**

[1054] Learn more arrow from icons.svg

---

assets/styles/components/_Block.scss

Bottom space for tag-title(s) placed in blocks.
Check bottom space of tag-title(s).
**Checklist**
Close QualityUnit/web-issues#1056

[1056] Tag title bottom space

---

assets/scripts/static/crm.js
base-scripts.php

add twitter ads tracking
**Checklist**
Close QualityUnit/web-issues#1064

[1064] feat: add twitter ads tracking

---

assets/styles/components/BlockVideo.scss

block video gradient
**Checklist**

fix: block video gradient

---

lib/includes/affiliate-manager/affiliate-manager-layout.php
templates/content-single-ms_directory.php

remove mail and phone from affiliate managers
**Checklist**

fix: remove mail and phone from affiliate managers

---

lib/includes/affiliate-manager/affiliate-manager-layout.php
templates/content-single-ms_directory.php

- add directories manager contacts back
**Checklist**

feat: add directories manager contacts back

---

assets/styles/components/_Block.scss
assets/styles/components/_DemoBar.scss
assets/styles/layouts/_Post.scss
templates/footer.php

multiple small fixes
**Checklist**
Close QualityUnit/web-issues#1063
Close QualityUnit/web-issues#1066
Close QualityUnit/web-issues#1073
Close QualityUnit/web-issues#1076
Close QualityUnit/web-issues#1079

[1063] fix: multiple small fixes

---

assets/styles/app.scss
assets/styles/components/EnhancedFaq.scss
base-scripts.php
base.php
lib/assets.php
templates/head.php

Core Web Vitals Optimisation
**Checklist**
Close QualityUnit/web-issues#995

[995] Core Web Vitals Optimisation

---

lib/shortcodes/alternatives.php
lib/shortcodes/signup-form-network.php
lib/shortcodes/signup-form-trial.php
lib/shortcodes/signup-form.php
lib/shortcodes/signup-sidebar.php
template-trial-network.php
templates/footer.php

- fix wrong links
**Checklist**
Close QualityUnit/web-issues#1073

[1073] fix: repair wrong links

---

assets/styles/common/_global.scss
assets/styles/layouts/_Post.scss

Everything
**Checklist**
Close QualityUnit/web-issues#1063
Close QualityUnit/web-issues#1079

[1063] fix: signup sidebar padding

---

assets/styles/common/_global.scss
assets/styles/components/_Boxes.scss

Homepage boxes styles.
Margin between last section and footer.
Check homepage changes according figma comments.
**Checklist**
Close QualityUnit/web-issues#1057

[1057] New homepage design feedback

---

assets/styles/components/_HeroHeadlineHome.scss

Overflow only for desktop resolutions.
Check homepage scroll on mobile
**Checklist**
Close QualityUnit/web-issues#1084

[1084] homepage scroll issue

---

contactus-box.php
templates/footer.php

- nofollow links in contact us element
**Checklist**

feat: nofollow links in contact us element

---

lib/includes/affiliate-manager/archive.php

- wrong affiliate link in the list
**Checklist**

fix: wrong affiliate link in the list

---

assets/styles/layouts/_Post.scss
lib/includes/affiliate-manager/affiliate-manager-layout.php
templates/content-archive-ms_glossary.php
templates/content-single-ms_directory.php

important note added to Affiliate Directory
**Checklist**
Close QualityUnit/la-marketing#2676

[2676] important note

---

assets/scripts/custom/blogLazyLoad.js
assets/styles/components/_AwardsHeroHeader.scss

Fixes blog lazyloading, awards in home header
**Checklist**
Close QualityUnit/web-issues#1061
Close QualityUnit/web-issues#1095

[1095] fix: blog lazyloading, awards in home header

---

assets/styles/components/BlockPricingNew.scss

Pricing block title font size was changed.
Check Pricing block design.
**Checklist**
Close QualityUnit/web-issues#806

[806] Pricing block title

---

assets/styles/components/_AwardsHeroHeader.scss

Removing custom elementor CSS from hero header and changing Awards position
**Checklist**
Close QualityUnit/web-issues#1097

[1097] fix: small fix to awards due to custom elementor styles (removed)

---

assets/styles/components/BlockPricingNew.scss

Pricing section variants only with network or program boxes.
Check variant of pricing section according figma designs:
[only program](https://www.figma.com/file/OYXspoqgXW42SdMxh4MZ3N/PAP-WEB-RfD---Affiliate-program-software?node-id=0%3A1&t=Ub0NikVBEsR71rHA-0)
[only network](https://www.figma.com/file/dmI1wp6K4s2ZoVZAVRSon8/PAP-WEB-RfD---Affiliate-network-software?node-id=424%3A932&t=KQMiZA2D8Fh8Hzag-0)
**Checklist**
Close QualityUnit/web-issues#1080

[1080] Pricing section variants

---

assets/styles/pages/Archive.scss
assets/styles/pages/Category.scss

- remove emoji from no results found page
**Checklist**
Close QualityUnit/web-issues#1102

[1102] fix: remove emoji from no results found page

---

assets/styles/components/_CookieBar.scss

- hide german cookie bar
**Checklist**
Close QualityUnit/web-issues#1131

[1131] fix: hide german cookie bar

---

assets/styles/components/BlockPricingNew.scss
assets/styles/components/_BlockIcons.scss

Blocks styles changes according [figma comments](https://www.figma.com/file/coWj1OqjAQ5IQYZ7QNyZGS/PAP-WEB-RfD---Automation?node-id=0%3A1&t=Ys3zwDaCWbA1knxH-0).
Check styles changes according [figma comments](https://www.figma.com/file/coWj1OqjAQ5IQYZ7QNyZGS/PAP-WEB-RfD---Automation?node-id=0%3A1&t=Ys3zwDaCWbA1knxH-0).
**Checklist**
Close QualityUnit/web-issues#1070

[1070] Blocks styles changes according figma comments

---

assets/scripts/static/crm.js

- send ga4 id to crm
**Checklist**
Close QualityUnit/la-marketing#2486

[2486] feat: send ga4 id to crm

---

assets/styles/components/_HeroHeadlineHome.scss
composer.lock

Hero image centered and icons.svg update.
Check new bullseye icon and position of hero images.
**Checklist**
Close QualityUnit/web-issues#1071

[1071] Hero image centered and icons svg update

---

assets/styles/components/_HeroHeadlineHome.scss

Fixed horizontal position of hero image.
Check hero image.
**Checklist**
Close QualityUnit/web-issues#1071

[1071] Hero image position

---

templates/content-single-ms_directory.php

Moved manager_industry() function from loop, because of fatal error.
Check single directory templates.
**Checklist**
Close QualityUnit/web-issues#1166

[1166] Manager industry function redeclaration

---

assets/styles/layouts/_Pricing.scss

Pricing section alignment fix.
Check pricing section alignment.
**Checklist**
Close QualityUnit/web-issues#1208

[1208 Pricing section alignment fix

---

base-scripts.php

GA4 domain linker fixed
**Checklist**
Close QualityUnit/web-issues#1428

[1428] fix: GA4 domain linker

---

composer.lock

Adding webinars icon
Close QualityUnit/web-issues#1526

[1526] fix: adding webinars icon from icons branch

---

lib/post-types/directory.php
templates/content-single-ms_directory.php

added support editor to postype directories 
**Checklist**
Close QualityUnit/web-issues#1624

[1624] Support for the_content() in Directories

---

lib/shortcodes/signup-form.php
templates/content-single-ms_directory.php

Changed texts 
**Checklist**
Close QualityUnit/web-issues#1651

[1651] Update PAP trial CTA text

---

assets/styles/components/BlockVideo.scss

Close QualityUnit/web-issues#1965

[1965] fix: block video  overlay

---

assets/styles/components/_HeaderLanguageSwitcher.scss

fixed one line with bad selector.
**Checklist**
Close QualityUnit/web-issues#1974

[1974] Align the languague switchers on PAP

---

assets/styles/shortcodes/CTA.scss

detected and reported bug in the urslab web. But I modified the styles so that it works even without the urslab plugin.
**Checklist**
Close QualityUnit/web-issues#1488

[1488] Visual Bugs on CTA Butons in Slovak Translation

---

assets/styles/common/_animations.scss
assets/styles/components/HorizontalTabs.scss

Fixed styles for horizontal tabs and some code cleanup
**Checklist**
Close QualityUnit/web-issues#2028

[2028] Element is not displaying correctly on PAP product pages

---

assets/scripts/custom/blogLazyLoad.js
assets/styles/common/_global.scss
templates/content-archive.php

blog lazyloading binded to loader instead of cached footer
Close QualityUnit/web-issues#2085

[2085] fix: blog lazyloading binded to loader instead of cached footer

---

assets/styles/components/_HeroBanner.scss

added styles for all elements in text editor for elementor
**Checklist**
Close QualityUnit/web-issues#2124

[2124] added styles for all elements in text editor for elementor

---

templates/content-single-ms_academy.php

I replaced old code with shortcode from the urslab for generating description in compact header
**Checklist**
Close QualityUnit/web-issues#1980

[1980] fixed description on academy single

---

assets/styles/app.scss
assets/styles/shortcodes/_UrlslabFaq.scss
templates/content-single-ms_features.php
templates/content-single-ms_templates.php
templates/content-single.php

I added styles for the FAQ section and I added the FAQ sections where it was missing
**Checklist**
Close QualityUnit/web-issues#2248

[2248] LA, PAP : please change FAQ from double collumn to one.

---

assets/scripts/app/app.js

Deleted script which adding target blank to links
**Checklist**
Close QualityUnit/web-issues#2421

[2421] deleted script which adding target blank to links

---

assets/styles/common/_elementor.scss

i added min-height on elementor videos.
**Checklist**
Close QualityUnit/web-issues#2391

[2391] fix video size in PAP page

---

templates/header.php

I added urlslab-skip-all class to header for language switcher
**Checklist**
Close QualityUnit/web-issues#2457

[2457]  PAP articles open in new tab

---

functions/redirects.php

i added redirect for videos categories
**Checklist**
Close QualityUnit/web-issues#2531

[2531] Added redirect for videos categories

---

templates/content-single-ms_integrations.php

I replaced h2 title "Partner" with post title + "integration"
**Checklist**
Close QualityUnit/web-issues#2580

[2580] Incorrect H2 "Partner" on integration posts PAP

---

templates/footer.php

I rewrite tooltips in footer. Liveagent -> Post Affiliate Pro's
**Checklist**
Close QualityUnit/web-issues#2583

[2583] Renamed incorrect tooltips for mobile phone in footer

---

lib/assets.php
lib/includes/affiliate-manager/affiliate-manager.php

I moved css styles from body to head for better CLS
**Checklist**
Close QualityUnit/web-issues#2592

[2592] Rearrange the order in which CSS files load to minimise CLS

---

lib/shortcodes/signup-form-network.php
lib/shortcodes/signup-form.php
template-trial-network.php
template-trial.php

I replaced new text for trial forms 
**Checklist**
Close QualityUnit/web-issues#2618

[2618] Changing duration of trials

---

assets/scripts/app/toggleVisibility.js
assets/scripts/app/trialSticky.js
assets/styles/Elementor.scss
assets/styles/app.scss
assets/styles/components/TrialStickyButton.scss
assets/styles/components/_ContactUs.scss
templates/footer.php

I added new sticky trial button and optimized contact us button for correctly working.
**Checklist**
Close QualityUnit/web-issues#1327
Close QualityUnit/web-issues#2626

[1327] Pinned CTA Buttons on Mobiles

---

assets/scripts/app/videoTranscript.js
assets/styles/app.scss
assets/styles/shortcodes/VideoTranscript.scss
templates/content-single-ms_videos.php

I added missing styles for urlslab transcript shortcode and edited som styles for better visual
**Checklist**
Close QualityUnit/web-issues#2628

[2628] The video transcript feature has a broken design on PAP

---

assets/styles/components/AnnouncementBar.scss

Fixes responsivity of annoucement bar
Close QualityUnit/web-issues#2658

[2658] fix: responsivity and image position

---

assets/styles/components/AnnouncementBar.scss

I2658 annoucement bar responsivness v2

---

assets/styles/components/AnnouncementBar.scss

[Describe what was changed in the Pull Request](fix: position of header banner image)
Close QualityUnit/web-issues#2658

[2658] fix: position of header banner image

---

assets/styles/components/MerchantAffiliate.scss

I rewrote the css for merchant affiliate element to work correctly
**Checklist**
Close QualityUnit/web-issues#2657

[2657] Take a tour - video bug

---

assets/styles/components/AnnouncementBar.scss

image position fix when URLslab wraps it into <picture> tag
Close QualityUnit/web-issues#2658

[2658] fix: image position

---

assets/scripts/custom/IconTabs.js
assets/styles/components/IconTabs.scss

I fixed styles for icon tab element
**Checklist**
Close QualityUnit/web-issues#2762

[2762] Visual bugs on https://www.postaffiliatepro.com/automation/

---

assets/scripts/app/demobar.js
templates/footer.php

I added condition in JS for demo bar and added de url for disable demo bar on this page
**Checklist**

Fix demobar on the trial page in DE version PAP

---

contactus-box.php
templates/footer.php

I changed our whatsapp numbers in the contact us button and in the footer
**Checklist**
Close QualityUnit/web-issues#2799

[2799] Change of our WA number in multiwidget on PostAffiliatePro website

---

assets/styles/components/AnnouncementBar.scss

fix: image position

---

assets/scripts/custom/socialShareFunctions.js
assets/styles/components/_BlogShare.scss
assets/styles/components/_ContactUs.scss
contactus-box.php
templates/content-single.php

I added new js functions which are called in button element as onClick attribut and some styles
**Checklist**
Close QualityUnit/web-issues#2785

2785 Rework Contact us element on PAP

---

assets/styles/components/BlockPricingNew.scss

I rewrote some css to fix broken visual on price block element for elementor
**Checklist**
Close QualityUnit/web-issues#2854

[2854] Pricing on PAP Product pages is broken

---

.github/workflows/build-test-qu-howtos.yml
.github/workflows/build-test.yml
.github/workflows/eslint.yml
.github/workflows/stylelint.yml
lib/widgets/qu-howtos/package.json
lib/widgets/qu-howtos/yarn.lock
package.json
yarn.lock

Upgrading to Node 20
Close QualityUnit/web-issues#2863

[2863] feat: upgrade to node 20

---

.github/workflows/publish-release.yml

Describe what was changed in the Pull Request
**Checklist**
Close QualityUnit/web-issues#2863

[2863 ] fix: i2863_node_build_to_20

---

assets/styles/components/Table.scss
functions/components-import.php

Describe what was changed in the Pull Request
**Checklist**
Close QualityUnit/web-issues#[ISSUE_NUMBER]

fix: assets loading only when in edit mode

---

elementor.php
front-page.php
templates/footer.php

hiding good hands banner in other languages
Close QualityUnit/web-issues#2876

[2876] fix: good hands banner hiding

---

assets/images/contact/chatbot.svg
assets/styles/components/_ContactUs.scss
contactus-box.php

chatbot integration
Close QualityUnit/web-issues#2885

[2885] feat: chatbot integration

---

assets/styles/common/_global.scss
assets/styles/components/_ContactUs.scss
base-scripts.php

replacing contact form with chatbot on selected pages
Close QualityUnit/web-issues#2885

[2885] feat: replacing contact form with chatbot on selected pages

---

assets/styles/components/_GoodHands.scss

fix: hiding image on mobile

---

base-scripts.php
contactus-box.php

loading contact us chatbot on cookies only
Close QualityUnit/web-issues#2885

[2885] fix: loading contact us chatbot on cookies only

---

assets/scripts/app/tooltips.js
assets/scripts/vendor/popper.js
assets/styles/components/AffiliateSignup.scss
assets/styles/elements/_Tooltip.scss
composer.lock
gulpfile.js
lib/assets.php

affiliate program icons, new tooltip implemented, safari bugfixes
Close QualityUnit/web-issues#1616

[1616] affiliate program icons

---

assets/styles/elements/_Tooltip.scss

fix: info icon pricing tooltip

fix: info icon pricing tooltip

---

assets/styles/elements/_Tooltip.scss

Describe what was changed in the Pull Request
**Checklist**
Close QualityUnit/web-issues#[ISSUE_NUMBER]

fix: tooltip in checklists

---

assets/styles/components/MerchantAffiliate.scss

Fixed styles for merchant element
**Checklist**
Close QualityUnit/web-issues#2912

[2912] PAP /tour page missing image

---

assets/styles/components/HeroBig.scss

I added style for center text in hero big element
**Checklist**
Close QualityUnit/web-issues#2912

[2912] Centering text in hero big element

---

assets/styles/components/_ContactUs.scss
composer.lock
contactus-box.php

contact us servers status verification
Close QualityUnit/web-issues#2021

[2021] feat: contact us servers status verification

---

lib/cleaner/assets.php

Added filter for disable pagination in yoast seo
**Checklist**
Close QualityUnit/web-issues#2827

[2827] Removing yoast seo pagination on PAP

---

assets/styles/common/_mixins.scss
assets/styles/components/AffiliateSignup.scss

affiliate program signup scrollbar fix
Close QualityUnit/web-issues#1616

[1616] fix: affiliate program signup scrollbar

---

lib/shortcodes/signup-form-network.php

Changed path for `set_custom_source` in `signup-form-network.php`
**Checklist**

Fix bad path to styles for affiliate network form

---

lib/shortcodes/signup-sidebar.php
templates/content-single-ms_directory.php

[Describe what was changed in the Pull Request](fix: cls)
Close QualityUnit/web-issues#2971

[2971] fix: cls

---

assets/styles/components/_Login.scss
lib/shortcodes/login.php

fix: login

---

lib/shortcodes/login.php

fix: login jquery loading

---

assets/styles/components/compactHeader.scss
functions/import-functions.php
lib/custom-blocks/compact-header.php
templates/footer.php

I expanded breadcrumb function, disabled domebar on affiliate managers page and fixed styles for tooltips in tags.
**Checklist**
Close QualityUnit/web-issues#2937
Close QualityUnit/web-issues#3252

[2937] update structure of affiliate managers page

---

assets/styles/Elementor.scss
assets/styles/app.scss
assets/styles/common/common.scss
assets/styles/components/compactHeader.scss
functions/content-filters-learn-more.php
lib/assets.php
lib/includes/affiliate-manager/affiliate-manager-layout.php
lib/shortcodes/signup-sidebar.php
template-academy.php
template-blog-header.php
template-blog.php
templates/content-archive-ms_directory.php
templates/content-archive-ms_glossary.php
templates/content-archive.php
templates/head.php

multiple cls issues on blog archive, glossary and directory archives
Close QualityUnit/web-issues#2976

[2976] fix: multiple cls issues on blog archive, glossary and directory

---

functions/import-functions.php

I added link to breadcrumb for the affiliate managers
**Checklist**
Close QualityUnit/web-issues#2982

[2982] Not valid Schema.org in breadcrumbs

---

assets/styles/components/_SignupSidebar.scss

I rearranged the styles for the signup form
**Checklist**
Close QualityUnit/web-issues#2985

[2985] Broken Sign Up form

---

functions/components-import.php
lib/shortcodes/signup-affiliate.php

I removed the import for the old CSS file associated with this form.
**Checklist**

Fix console error on the Affiliate program page

---

templates/header.php

I fixed broken book a call button in header
**Checklist**
Close QualityUnit/web-issues#3009

[3009] Book a Call button issues 

---

assets/styles/components/_HeaderLanguageSwitcher.scss
assets/styles/layouts/Header.scss

I added correct z-index for the language switcher and login menu
**Checklist**
Close QualityUnit/web-issues#3010

[3010]  PAP language switcher overlapped

---

lib/cleaner/assets.php

I removed code which removing gutenberg styles for logged out users.
**Checklist**
Close QualityUnit/web-issues#3011

[3011] Media not aligned according to setting

---

assets/scripts/static/crmInstaller.js

Fixed wrong Capterra tracking script
Close QualityUnit/web-issues#3014

fix: incorrect capterra tracking script

---

base-scripts.php
contactus-box.php

I replaced urlslab chat with flowhunt chatbot
**Checklist**
Close QualityUnit/web-issues#3054

[3054] Use flowhunt chatbot everywhere

---

base-scripts.php

tracking script
Close QualityUnit/web-issues#3078

[3078] fix: tracking scripts

---

functions/elementor-content-filters.php
lib/shortcodes/awards-small.php

saving with awards banner active causing error fixed
Close QualityUnit/web-issues#3087

[3087] fix: saving with awards banner active

---

assets/styles/elements/_PostTypography.scss

Changes proposed in this Pull Request
I rewrote the styles for the lists because after updating gutenberg the list has a new class
**Checklist**
Close QualityUnit/web-issues#3088

[3088] Rewrite css for checkmarks in lists

---

functions.php

fixed syntax in function

---

assets/scripts/app/queryParamsToUrls.js

adds query params to every liveagent url on webpage
Close QualityUnit/web-issues#3019

[3019] feat: adds query params to every postaffiliate url on page

---

assets/scripts/app/queryParamsToUrls.js

added new parameters for the blacklist
**Checklist**
Close QualityUnit/web-issues#3162

[3162] Blacklist some parameters which are not forwarded to other links

---

assets/scripts/app/queryParamsToUrls.js
functions/urlslab-related-posts.php

Changes proposed in this Pull Request
disabled js for adding query params to links
**Checklist**
Close QualityUnit/web-issues#3162

[3162] Disabled js for query param

---

assets/styles/layouts/Footer.scss
templates/footer.php

I added capterra and crozdesk widgets to our footer and created reviews schemas for this widgets.
**Checklist**
Close QualityUnit/web-issues#3180

[3180] Revalidate Schema.org definition

---

assets/styles/layouts/Footer.scss
templates/footer.php

I have removed schemas and imgs for reviews from the footer
**Checklist**
Close QualityUnit/web-issues#3209

[3209] Implement our own custom footer star rating with Schema.org markup

---

contactus-box.php

i added variable $en_slug for initialized before we use it
**Checklist**
Close QualityUnit/web-issues#3195

[3195] Undefined variable $en_slug in contactus-box.php

---

templates/header.php

I removed announcement banner from the pricing page
**Checklist**
Close QualityUnit/web-issues#3240

[3240] Remove Cross-Selling Banner / Pop-up

---

.github/workflows/add_to_project.yml

i testing why workflows `add_to_project` is broken

chore: change path

---

base-scripts.php

make chatbot input placeholder translatable
Close QualityUnit/web-issues#3177

[3177] fix: make chatbot input placeholder translatable

---

.github/workflows/add_to_project.yml

chore: back to old files

---

assets/styles/components/BlockCoupon.scss
assets/styles/shortcodes/Countdown.scss
lib/shortcodes/countdown.php

I changed a couple of styles in the block coupon element
**Checklist**
Close QualityUnit/web-issues#3688

[3688] Black Friday / Cyber Monday promotion 2024

---

assets/styles/components/BlockPricingNew.scss
assets/styles/components/_CategoryItem.scss
elementor.php
functions/taxonomies.php
functions/urlslab-related-posts.php
lib/cleaner/assets.php
lib/post-types/alternatives.php
lib/shortcodes/alternatives.php
templates/content-archive-ms_academy.php
templates/content-archive-ms_templates.php
templates/content-page.php

Multiple bugfixes 
Close QualityUnit/web-issues#3272
Close QualityUnit/web-issues#3277
Close QualityUnit/web-issues#3280
Close [QualityUnit/web-issues#3658](https://github.com/QualityUnit/la-marketing/issues/3658)

[3272] fix: multiple bugfixes

---

assets/scripts/app/app.js
assets/scripts/custom/countdown.js

i fixed countdown js for safari and fixed copy coupon button
**Checklist**
Close QualityUnit/web-issues#3305

 [3305]: PAP Black Friday pricing banner - Copy coupon - button does not work

---

assets/scripts/custom/sidebar_items_slider.js
assets/scripts/custom/sidebar_toc.js

i removed loadimg function with problem
**Checklist**
Close QualityUnit/web-issues#3259

[3259]: Fix code scanning alert - DOM text reinterpreted as HTML 

---

lib/shortcodes/awards-small.php

I return back set_custom_source what changed in the PR https://github.com/QualityUnit/postaffiliatepro-theme/pull/904/commits/b07a60a045aab902b7003a00cd19d143b1bb4093
**Checklist**
Close QualityUnit/web-issues#3039

[3039] [Bug]: Impossible to resubmit sign up form

---

assets/scripts/custom/custom_lightbox_youtube.js

fixed youtube player on the windows OS 
**Checklist**
Close QualityUnit/web-issues#3197

[3197] Replace Homepage Image with Embedded Video

---

assets/styles/components/_CategoryItem.scss

Added styles for images for correct view on integration-methods page PAP
- Go to integration-methods page on PAP and check visual view of images
**Checklist**
Close QualityUnit/web-issues#3314

[3314] - fix: changed styles for images on the integration methods list

---

assets/styles/layouts/Footer.scss
lib/setup.php
lib/shortcodes/good-hands.php
templates/header.php

Changed color scheme for buttons on homepage
- Go to homepage and check color scheme in buttons, need to be revert result
**Checklist**
Close QualityUnit/web-issues#3306

[3306] - fix: changed color scheme for buttons on homepage

---

assets/styles/layouts/tests/RequestDemo.scss

Fix jump on demo page between sections changing style for iframe.
- Go to demo page (https://www.postaffiliatepro.com/demo/) and check
visual page load behavior
**Checklist**
Close QualityUnit/web-issues#3278

[3278] - fix: added fix height for iframe on demo page

---

ai-chat-button.php
assets/styles/components/_ContactUs.scss
base-scripts.php
chat-button.php
contactus-box.php

- replaced flowhunt script for chatbot with LA script for chatbot
- fix chat with human
- removed conditions for control cookies accaptance from LA widgets
**Checklist**
Close QualityUnit/web-issues#3343

[3343] Request for replacement of chatbot button in contact multiwidget on PAP

---

base-scripts.php
contactus-box.php

- i rewrite the text in multiwidget "chat with agent" to "chat"
- removed Ai chatbot from multiwidget
- added new chat to pricinge and removed multiwidget
- fixed duplicate script after click on the button for accept cookies
**Checklist**
Close QualityUnit/web-issues#3349

[3349] chat & chatbot widget adjustments on the website

---

base-scripts.php

Added script for CrozDesk Conversion Tracking
- Go to trial page and check working CrozDesk Conversion Tracking
**Checklist**
Close QualityUnit/web-issues#3348

[3348] - feat: added script for CrozDesk Conversion Tracking

---

lib/shortcodes/cta.php
lib/shortcodes/good-hands.php
lib/shortcodes/signup-form-network.php
lib/shortcodes/signup-form.php
template-trial-network.php
template-trial.php
templates/content-single-ms_directory.php

Changed "14" to "30" days free trial on whole site
- Go to all page of site and check that 14 changed to 30 days free trial
**Checklist**
Close QualityUnit/web-issues#3741

[3741] - feat: changed "14" to "30" days free trial on whole site

---

assets/styles/components/BlockCoupon.scss
assets/styles/shortcodes/Countdown.scss

customized banner for spring sale
**Checklist**
Close QualityUnit/web-issues#3791

[3791] Spring Deal 2025 Promotion

---

assets/styles/components/_Numbers.scss

Changed z-index "Numbers" section
- Go to /services/integration/ page and check
"How does the integration service work?" section
**Checklist**
Close QualityUnit/web-issues#3359

[3359] - fix: changed z-index "Numbers" section

---

templates/footer.php

Changed link for x/twitter in footer
- Go to any page with footer and check link to x/twitter
**Checklist**
Close QualityUnit/web-issues#3396

[3396] - fix: changed link for x/twitter in footer

---

assets/styles/common/_variables.scss
assets/styles/components/BlockCoupon.scss
assets/styles/shortcodes/Countdown.scss

Changed styles for coupon banner
- Go to /pricing/ page and check visual view
coupon banner on all devices
**Checklist**
Close QualityUnit/web-issues#3391

[3391] - fix: changed styles for coupon banner

---

assets/scripts/static/crmInstaller.js

Refactor tracing scripts and added script for linkedin tracking
**Checklist**
Close QualityUnit/web-issues#3928

[3928] Tracking Tag for LinkedIn Ads for PAP

---

assets/styles/pages/TrialRedesign.scss
lib/shortcodes/signup-form-network.php
lib/shortcodes/signup-form.php

I added labels "Limited pricing offer" to trial pages and i hid  label with credit card info
**Checklist**
Close QualityUnit/web-issues#3938

[3938] Communication of the limited prices on trial page and HP
